spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true

server:
  port: ${SERVER_PORT:8080}

app:
  jwt:
    secret: "mySecretKeymySecretKeymySecretKeymySecretKey1234567890123456"
